# Generated by Django 4.0.7 on 2022-09-15 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AzCliGenTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDosProtectionPlan',
            fields=[
                ('resourcebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AzCliGenTool.resourcebase')),
            ],
            bases=('AzCliGenTool.resourcebase',),
        ),
        migrations.AddField(
            model_name='virtualnetwork',
            name='dns_server',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
